---
# tasks file for concourse-ci
- name: Fetch Concourse binary.
  get_url:
    url: "https://github.com/concourse/concourse/releases/download/v{{ concourse_version }}/concourse_linux_amd64"
    dest: /usr/local/bin/concourse
    owner: root
    group: root
    mode: "0755"
    checksum: "sha512:{{ concourse_checksum_map.concourse.concourse_version] }}"
  notify: restart concourse
  when: concourse_is_server

- name: Fetch Fly binary.
  get_url:
    url: "https://github.com/concourse/fly/releases/download/v{{ concourse_version }}/fly_linux_amd64"
    dest: /usr/local/bin/fly
    owner: root
    group: root
    mode: "0755"
    checksum: "sha512:{{ concourse_checksum_map.fly.concourse_version }}"
  when: not concourse_is_server
