---
- name: Configure Concourse CI server.
  hosts: concourse-server
  roles:
    - role: concourse-ci

- name: Configure Concourse CI fly client.
  hosts: concourse-client
  roles:
    - role: concourse-ci
      concourse_is_server: no
